# Generated by Django 2.2.5 on 2020-03-15 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200310_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='desc',
        ),
    ]
