# Generated by Django 2.2.5 on 2020-03-15 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_title_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title_image',
            field=models.ImageField(default='title_images/default.png', height_field=300, upload_to='title_images', width_field=750),
        ),
    ]
