# Generated by Django 2.2.5 on 2020-03-16 14:50

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20200316_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='desc',
            field=ckeditor.fields.RichTextField(verbose_name='摘要'),
        ),
    ]
