# Generated by Django 2.2.5 on 2020-03-21 14:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyVisitStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_visit_number', models.PositiveIntegerField(default=0, verbose_name='每天访问量')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='日期')),
            ],
            options={
                'verbose_name': '每天访问量',
            },
        ),
        migrations.CreateModel(
            name='IPStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100, verbose_name='用户访问IP')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='访问时间')),
            ],
            options={
                'verbose_name': '用户访问IP',
            },
        ),
        migrations.CreateModel(
            name='VisitStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_number', models.IntegerField(default=0, verbose_name='访问总数')),
            ],
            options={
                'verbose_name': '访问总数',
            },
        ),
    ]
