# Generated by Django 2.2.5 on 2020-03-21 15:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_auto_20200321_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipstatistic',
            name='ip_domain',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='IP归属地'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ipstatistic',
            name='ip',
            field=models.CharField(max_length=30, verbose_name='用户访问IP'),
        ),
    ]
