# Generated by Django 2.2.5 on 2020-03-01 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category_created_time'),
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Link',
            new_name='Comment',
        ),
    ]
